pool:

  name: Hosted Ubuntu 1604



steps:

- task: Docker@2

  displayName: 'buildAndPush frontend angular'

  inputs:

    containerRegistry: 'Azure Public RMITPOC'

    repository: frontendangular

    Dockerfile: Docker.Client/Dockerfile

    buildContext: Docker.Client

    tags: |
     $(Build.BuildId)
     latest



- task: Docker@2

  displayName: 'buildAndPush backend dotnetcore'

  inputs:

    containerRegistry: 'Azure Public RMITPOC'

    repository: backenddotnetcore

    Dockerfile: WebCore.API/Dockerfile

    buildContext: WebCore.API

    tags: |
     $(Build.BuildId)
     latest


